Update rust toolchain to 1.70.0
Since we are not using exact version of dependencies, some of our dependencies have been updated to require rust 1.70.0.

This commit update our toolchain to match that requirement.

Current error message on the `master` branch on 1.66.0:
```
cargo +1.66.0 clippy --all-targets -- -D warnings
error: package `toml v0.8.12` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.66.0
Either upgrade to rustc 1.70 or newer, or use
cargo update -p toml@0.8.12 --precise ver
where `ver` is the latest version of `toml` supporting rustc 1.66.0
```